const media = [
    {
      title: "Inception",
      type: "Movie",
      Released: "2010-07-16",
      Runtime: "148 min",
      Genre: "Action, Adventure, Sci-Fi",
      Director: "Christopher Nolan",
      Writer: "Christopher Nolan",
      Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
      Plot: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
      Language: "English",
      Country: "USA, UK",
      Awards: "Won 4 Oscars; 157 wins & 220 nominations total",
      Poster: "https://image.tmdb.org/t/p/original/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
      imdbID: "tt1375666"
    },
    {
      title: "The Dark Knight",
      type: "Movie",
      Released: "2008-07-18",
      Runtime: "152 min",
      Genre: "Action, Crime, Drama",
      Director: "Christopher Nolan",
      Writer: "Jonathan Nolan, Christopher Nolan",
      Actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
      Plot: "When the menace known as the Joker wreaks havoc, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
      Language: "English",
      Country: "USA, UK",
      Awards: "Won 2 Oscars; 159 wins & 163 nominations total",
      Poster: "https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      imdbID: "tt0468569"
    },
    {
      title: "Interstellar",
      type: "Movie",
      Released: "2014-11-07",
      Runtime: "169 min",
      Genre: "Adventure, Drama, Sci-Fi",
      Director: "Christopher Nolan",
      Writer: "Jonathan Nolan, Christopher Nolan",
      Actors: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
      Plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
      Language: "English",
      Country: "USA, UK",
      Awards: "Won 1 Oscar; 44 wins & 148 nominations total",
      Poster: "https://image.tmdb.org/t/p/original/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      imdbID: "tt0816692"
    },
    {
      title: "Stranger Things",
      type: "TV Show",
      Released: "2016-07-15",
      Runtime: "42–142 min",
      Genre: "Drama, Fantasy, Horror",
      Director: "The Duffer Brothers",
      Writer: "The Duffer Brothers",
      Actors: "Millie Bobby Brown, Finn Wolfhard, Winona Ryder",
      Plot: "In 1980s Indiana, a group of young friends witness supernatural forces and secret government exploits.",
      Language: "English",
      Country: "USA",
      Awards: "Won 12 Primetime Emmys; 114 wins & 323 nominations total",
      Poster: "https://image.tmdb.org/t/p/original/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
      imdbID: "tt4574334"
    },
    {
      title: "Attack on Titan",
      type: "Anime",
      Released: "2013-04-07",
      Runtime: "24 min",
      Genre: "Animation, Action, Adventure",
      Director: "Tetsurō Araki",
      Writer: "Hajime Isayama",
      Actors: "Yuki Kaji, Marina Inoue, Josh Grelle",
      Plot: "After his hometown is destroyed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans.",
      Language: "Japanese",
      Country: "Japan",
      Awards: "N/A",
      Poster: "https://m.media-amazon.com/images/I/61t9ie31jgL._AC_UF1000,1000_QL80_.jpg",
      imdbID: "tt2560140"
    },
    {
      title: "My Hero Academia",
      type: "Anime",
      Released: "2016-04-03",
      Runtime: "24 min",
      Genre: "Animation, Action, Adventure",
      Director: "Kenji Nagasaki",
      Writer: "Kōhei Horikoshi",
      Actors: "Daiki Yamashita, Justin Briner, Nobuhiko Okamoto",
      Plot: "A superhero-admiring boy enrolls in a prestigious hero academy and learns what it really means to be a hero.",
      Language: "Japanese",
      Country: "Japan",
      Awards: "N/A",
      Poster: "https://image.tmdb.org/t/p/original/phuYuzqWW9ru8EA3HVjE9W2Rr3M.jpg",
      imdbID: "tt5626028"
    },
    {
      title: "One Piece",
      type: "Anime",
      Released: "1999-10-20",
      Runtime: "24 min",
      Genre: "Animation, Action, Adventure",
      Director: "Konosuke Uda",
      Writer: "Eiichiro Oda",
      Actors: "Mayumi Tanaka, Tony Beck, Laurent Vernin",
      Plot: "Follows the adventures of Monkey D. Luffy and his pirate crew in order to find the greatest treasure ever left by the legendary Pirate, Gold Roger.",
      Language: "Japanese",
      Country: "Japan",
      Awards: "N/A",
      Poster: "https://image.tmdb.org/t/p/original/e3NBGiAifW9Xt8xD5tpARskjccO.jpg",
      imdbID: "tt0388629"
    },
    {
        title: "Breaking Bad",
        type: "TV Show",
        Released: "2008-01-20",
        Runtime: "49 min",
        Genre: "Crime, Drama, Thriller",
        Director: "Vince Gilligan",
        Writer: "Vince Gilligan",
        Actors: "Bryan Cranston, Aaron Paul, Anna Gunn",
        Plot: "A high school chemistry teacher turned methamphetamine producer navigates the dangers of the criminal underworld.",
        Language: "English",
        Country: "USA",
        Awards: "Won 16 Primetime Emmys; 154 wins & 247 nominations total",
        Poster: "https://image.tmdb.org/t/p/original/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
        imdbID: "tt0903747"
      },
      {
        title: "Death Note",
        type: "Anime",
        Released: "2006-10-03",
        Runtime: "23 min",
        Genre: "Animation, Crime, Drama",
        Director: "Tetsurō Araki",
        Writer: "Tsugumi Ohba",
        Actors: "Mamoru Miyano, Brad Swaile, Vincent Tong",
        Plot: "An intelligent high school student goes on a secret crusade to eliminate criminals using a deadly notebook that can kill anyone whose name is written in it.",
        Language: "Japanese",
        Country: "Japan",
        Awards: "N/A",
        Poster: "https://image.tmdb.org/t/p/original/iigTJJskR1PcjjXqxdyJwVB3BoU.jpg",
        imdbID: "tt0877057"
      },
      {
        title: "Friends",
        type: "TV Show",
        Released: "1994-09-22",
        Runtime: "22 min",
        Genre: "Comedy, Romance",
        Director: "David Crane, Marta Kauffman",
        Writer: "David Crane, Marta Kauffman",
        Actors: "Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc, Matthew Perry, David Schwimmer",
        Plot: "Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.",
        Language: "English",
        Country: "USA",
        Awards: "Won 6 Primetime Emmys; 77 wins & 220 nominations total",
        Poster: "https://image.tmdb.org/t/p/original/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
        imdbID: "tt0108778"
      }
]
export default media;
  